spring:
  h2:
    console:
      enabled: true       # H2 ?? ???
      path: /h2-console   # H2 ?? ??
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: user
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
